//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace linx_tablets.Hive {
    
    
    public partial class HiveProductStockHoldingRules {
        
        /// <summary>
        /// sqlDSorscleLastRunPoStock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource sqlDSorscleLastRunPoStock;
        
        /// <summary>
        /// ddlForecastAmountUsedBundlesExertisHive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlForecastAmountUsedBundlesExertisHive;
        
        /// <summary>
        /// btnUpdateForecastUsedBundlesExertisHive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdateForecastUsedBundlesExertisHive;
        
        /// <summary>
        /// ddlForecastAmountUsedBundlesExertis3PL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlForecastAmountUsedBundlesExertis3PL;
        
        /// <summary>
        /// btnUpdate3PLForecastWeeksUsedBundles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdate3PLForecastWeeksUsedBundles;
        
        /// <summary>
        /// pnlExertisHiveWeeksUsed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlExertisHiveWeeksUsed;
        
        /// <summary>
        /// ddlForecastAmountUsedExertisHive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlForecastAmountUsedExertisHive;
        
        /// <summary>
        /// btnUpdateExertisHiveForecastWeeksUsed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdateExertisHiveForecastWeeksUsed;
        
        /// <summary>
        /// ddlForecastAmountUsedExertis3PL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlForecastAmountUsedExertis3PL;
        
        /// <summary>
        /// btnUpdate3PLForecastWeeksUsed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdate3PLForecastWeeksUsed;
        
        /// <summary>
        /// txtSellThroughPercentage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSellThroughPercentage;
        
        /// <summary>
        /// sellThruRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator sellThruRegex;
        
        /// <summary>
        /// btnUpdateSellThroughOverwrite control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdateSellThroughOverwrite;
    }
}
