//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linx_tablets.SapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:sprx:ep:cust:UPDATE", ConfigurationName="SapService.ZWS_IN002_UPD_ZTAB")]
    public interface ZWS_IN002_UPD_ZTAB {
        
        // CODEGEN: Generating message contract since the operation Z_MMFM_IN002_UPD_ZTAB is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:sprx:ep:cust:UPDATE:ZWS_IN002_UPD_ZTAB:Z_MMFM_IN002_UPD_ZTABRequest", ReplyAction="urn:sap-com:sprx:ep:cust:UPDATE:ZWS_IN002_UPD_ZTAB:Z_MMFM_IN002_UPD_ZTABResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1 Z_MMFM_IN002_UPD_ZTAB(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:sprx:ep:cust:UPDATE:ZWS_IN002_UPD_ZTAB:Z_MMFM_IN002_UPD_ZTABRequest", ReplyAction="urn:sap-com:sprx:ep:cust:UPDATE:ZWS_IN002_UPD_ZTAB:Z_MMFM_IN002_UPD_ZTABResponse")]
        System.Threading.Tasks.Task<linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1> Z_MMFM_IN002_UPD_ZTABAsync(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMFM_IN002_UPD_ZTAB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMMSTR_CHARACT[] cH_CHARACTField;
        
        private string iM_MANUFACTURERField;
        
        private string iM_MANUF_PART_NOField;
        
        private string iM_MATERIALField;
        
        private string iM_TIMESTAMPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMMSTR_CHARACT[] CH_CHARACT {
            get {
                return this.cH_CHARACTField;
            }
            set {
                this.cH_CHARACTField = value;
                this.RaisePropertyChanged("CH_CHARACT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_MANUFACTURER {
            get {
                return this.iM_MANUFACTURERField;
            }
            set {
                this.iM_MANUFACTURERField = value;
                this.RaisePropertyChanged("IM_MANUFACTURER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_MANUF_PART_NO {
            get {
                return this.iM_MANUF_PART_NOField;
            }
            set {
                this.iM_MANUF_PART_NOField = value;
                this.RaisePropertyChanged("IM_MANUF_PART_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_TIMESTAMP {
            get {
                return this.iM_TIMESTAMPField;
            }
            set {
                this.iM_TIMESTAMPField = value;
                this.RaisePropertyChanged("IM_TIMESTAMP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMSTR_CHARACT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cHARACT_NAMEField;
        
        private string cHARACT_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CHARACT_NAME {
            get {
                return this.cHARACT_NAMEField;
            }
            set {
                this.cHARACT_NAMEField = value;
                this.RaisePropertyChanged("CHARACT_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CHARACT_VALUE {
            get {
                return this.cHARACT_VALUEField;
            }
            set {
                this.cHARACT_VALUEField = value;
                this.RaisePropertyChanged("CHARACT_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MMFM_IN002_UPD_ZTABResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMMSTR_CHARACT[] cH_CHARACTField;
        
        private string eX_SUBRCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMMSTR_CHARACT[] CH_CHARACT {
            get {
                return this.cH_CHARACTField;
            }
            set {
                this.cH_CHARACTField = value;
                this.RaisePropertyChanged("CH_CHARACT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_SUBRC {
            get {
                return this.eX_SUBRCField;
            }
            set {
                this.eX_SUBRCField = value;
                this.RaisePropertyChanged("EX_SUBRC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMFM_IN002_UPD_ZTABRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTAB Z_MMFM_IN002_UPD_ZTAB;
        
        public Z_MMFM_IN002_UPD_ZTABRequest() {
        }
        
        public Z_MMFM_IN002_UPD_ZTABRequest(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTAB Z_MMFM_IN002_UPD_ZTAB) {
            this.Z_MMFM_IN002_UPD_ZTAB = Z_MMFM_IN002_UPD_ZTAB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_MMFM_IN002_UPD_ZTABResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse Z_MMFM_IN002_UPD_ZTABResponse;
        
        public Z_MMFM_IN002_UPD_ZTABResponse1() {
        }
        
        public Z_MMFM_IN002_UPD_ZTABResponse1(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse Z_MMFM_IN002_UPD_ZTABResponse) {
            this.Z_MMFM_IN002_UPD_ZTABResponse = Z_MMFM_IN002_UPD_ZTABResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_IN002_UPD_ZTABChannel : linx_tablets.SapService.ZWS_IN002_UPD_ZTAB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_IN002_UPD_ZTABClient : System.ServiceModel.ClientBase<linx_tablets.SapService.ZWS_IN002_UPD_ZTAB>, linx_tablets.SapService.ZWS_IN002_UPD_ZTAB {
        
        public ZWS_IN002_UPD_ZTABClient() {
        }
        
        public ZWS_IN002_UPD_ZTABClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_IN002_UPD_ZTABClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_IN002_UPD_ZTABClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_IN002_UPD_ZTABClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1 linx_tablets.SapService.ZWS_IN002_UPD_ZTAB.Z_MMFM_IN002_UPD_ZTAB(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest request) {
            return base.Channel.Z_MMFM_IN002_UPD_ZTAB(request);
        }
        
        public linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse Z_MMFM_IN002_UPD_ZTAB(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTAB Z_MMFM_IN002_UPD_ZTAB1) {
            linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest inValue = new linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest();
            inValue.Z_MMFM_IN002_UPD_ZTAB = Z_MMFM_IN002_UPD_ZTAB1;
            linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1 retVal = ((linx_tablets.SapService.ZWS_IN002_UPD_ZTAB)(this)).Z_MMFM_IN002_UPD_ZTAB(inValue);
            return retVal.Z_MMFM_IN002_UPD_ZTABResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1> linx_tablets.SapService.ZWS_IN002_UPD_ZTAB.Z_MMFM_IN002_UPD_ZTABAsync(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest request) {
            return base.Channel.Z_MMFM_IN002_UPD_ZTABAsync(request);
        }
        
        public System.Threading.Tasks.Task<linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABResponse1> Z_MMFM_IN002_UPD_ZTABAsync(linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTAB Z_MMFM_IN002_UPD_ZTAB) {
            linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest inValue = new linx_tablets.SapService.Z_MMFM_IN002_UPD_ZTABRequest();
            inValue.Z_MMFM_IN002_UPD_ZTAB = Z_MMFM_IN002_UPD_ZTAB;
            return ((linx_tablets.SapService.ZWS_IN002_UPD_ZTAB)(this)).Z_MMFM_IN002_UPD_ZTABAsync(inValue);
        }
    }
}
